name: publish package

on:
  release:
    types: [published]

jobs:
  publish-package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out Git repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Pull latest verison info
        run: git pull origin main
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: "@donovan-maas-tbg"
          cache: "npm"

      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
